version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "this-is-not-a-production-password"
    networks:
      - default_network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default_network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default_network
    restart: unless-stopped
    
networks:
  default_network:
    driver: bridge
