name: 'ClientApp linting'

on:
    workflow_dispatch: ~
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node.js
              uses: actions/setup-node@v3.8.1

            - name: Restore dependencies and run linter
              run: cd $(pwd)/SpotlessSolutions.Web/ClientApp && npm install && npm run lint
