name: 'Server linting'

on:
    workflow_dispatch: ~
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

jobs:
    inspect-code:
        name: Code Quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET 8 SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Restore tools
              run: dotnet tool restore

            - name: Restore dependencies
              run: dotnet restore

            - name: InspectCode
              run: dotnet jb inspectcode $(pwd)/SpotlessSolutions.sln --no-build --output="codeinspections.xml" --verbosity=WARN

            - name: NVika
              run: dotnet nvika parsereport codeinspections.xml --treatwarningsaserrors

            - name: Run build
              run: dotnet build -c Release
